// Clues service worker (generated by deploy-public.mjs; do not edit here).
// Same-origin: network-first, cache fallback. CDN (version-pinned): cache-first.
const CACHE = 'clues-cache-v1';
self.addEventListener('install', () => { self.skipWaiting(); });
self.addEventListener('activate', (e) => {
    e.waitUntil(caches.keys()
        .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
        .then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
    const req = e.request;
    if (req.method !== 'GET') return;
    const sameOrigin = new URL(req.url).origin === self.location.origin;
    if (sameOrigin) {
        e.respondWith(fetch(req).then(res => {
            if (res && res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
            return res;
        }).catch(() => caches.match(req).then(hit => {
            if (hit) return hit;
            throw new Error('offline and not cached');
        })));
    } else {
        e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
            if (res && (res.ok || res.type === 'opaque')) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
            return res;
        })));
    }
});
